# Generated by Django 5.1 on 2024-12-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloque',
            new_name='GrupoCloracion',
        ),
        migrations.RenameField(
            model_name='cloracion',
            old_name='bloque_id',
            new_name='grupoclo_id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='dia_id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='especies_id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='fungicidas_id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='lineas_id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='obs_pro',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='trabajador_id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='turnos_id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='variedad_id',
        ),
        migrations.RemoveField(
            model_name='temperatura',
            name='dia_id',
        ),
        migrations.RemoveField(
            model_name='temperatura',
            name='lineas_id',
        ),
        migrations.RemoveField(
            model_name='temperatura',
            name='obs_tem',
        ),
        migrations.RemoveField(
            model_name='temperatura',
            name='trabajador_id',
        ),
        migrations.RemoveField(
            model_name='temperatura',
            name='turnos_id',
        ),
        migrations.CreateModel(
            name='GrupoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_grp', models.TextField(max_length=200)),
                ('dia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.dia')),
                ('especies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.especies')),
                ('fungicidas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.fungicidas')),
                ('lineas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.lineas')),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.sector')),
                ('trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.trabajador')),
                ('turnos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.turnos')),
                ('variedad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.variedad')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='grupopro_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.grupoproductos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GrupoTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_grt', models.TextField(max_length=200)),
                ('dia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.dia')),
                ('lineas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.lineas')),
                ('trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.trabajador')),
                ('turnos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.turnos')),
            ],
        ),
        migrations.AddField(
            model_name='temperatura',
            name='grupotem_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.grupotemperatura'),
            preserve_default=False,
        ),
    ]
