# Generated by Django 5.1 on 2025-01-04 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0002_rename_bloque_grupocloracion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloracion',
            options={'verbose_name': 'Cloracion', 'verbose_name_plural': 'Cloraciones'},
        ),
        migrations.AlterModelOptions(
            name='dia',
            options={'verbose_name': 'Dia', 'verbose_name_plural': 'Dias'},
        ),
        migrations.AlterModelOptions(
            name='dosificacion',
            options={'verbose_name': 'Dosificacion', 'verbose_name_plural': 'Dosificaciones'},
        ),
        migrations.AlterModelOptions(
            name='especies',
            options={'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.AlterModelOptions(
            name='fungicidas',
            options={'verbose_name': 'Fungicida', 'verbose_name_plural': 'Fungicidas'},
        ),
        migrations.AlterModelOptions(
            name='grupocloracion',
            options={'verbose_name': 'Grupo Cloracion'},
        ),
        migrations.AlterModelOptions(
            name='grupoproductos',
            options={'verbose_name': 'Grupo Producto'},
        ),
        migrations.AlterModelOptions(
            name='grupotemperatura',
            options={'verbose_name': 'Grupo Temperatura'},
        ),
        migrations.AlterModelOptions(
            name='lineas',
            options={'verbose_name': 'Linea', 'verbose_name_plural': 'Lineas'},
        ),
        migrations.AlterModelOptions(
            name='ppm',
            options={'verbose_name': 'PPM'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
        migrations.AlterModelOptions(
            name='temperatura',
            options={'verbose_name': 'Temperatura', 'verbose_name_plural': 'Temperaturas'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterModelOptions(
            name='variedad',
            options={'verbose_name': 'Variedad', 'verbose_name_plural': 'Variedades'},
        ),
        migrations.AlterField(
            model_name='ppm',
            name='hor_ppm',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='hor_tem',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
