# Generated by Django 5.1 on 2025-02-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0003_alter_cloracion_options_alter_dia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloracion',
            name='obs_clo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dosificacion',
            name='obs_dos',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='obs_ppm',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
