# Generated by Django 5.1 on 2025-03-02 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0006_alter_trabajador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosificacion',
            name='hor_dos',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='obs_ppm',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='phe_ppm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='hor_pro',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
