# Generated by Django 5.1 on 2025-03-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0007_alter_dosificacion_hor_dos_alter_ppm_obs_ppm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoproductos',
            name='sector_id',
        ),
    ]
