# Generated by Django 5.1 on 2025-03-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0008_remove_grupoproductos_sector_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoproductos',
            name='especies_id',
        ),
        migrations.RemoveField(
            model_name='grupoproductos',
            name='variedad_id',
        ),
        migrations.AddField(
            model_name='productos',
            name='especies_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.especies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='variedad_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.variedad'),
            preserve_default=False,
        ),
    ]
