# Generated by Django 5.1 on 2025-03-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0009_remove_grupoproductos_especies_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cod_pro',
            field=models.IntegerField(blank=True),
        ),
    ]
