# Generated by Django 5.1 on 2025-03-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0010_alter_productos_cod_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cod_pro',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
