# Generated by Django 5.1 on 2025-03-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0011_alter_productos_cod_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='bin_pro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='gas_pro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='kil_pro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ren_pro',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
