# Generated by Django 5.1 on 2025-03-10 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0012_alter_productos_bin_pro_alter_productos_gas_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='especies_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.especies'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='variedad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cloraciones.variedad'),
        ),
    ]
