# Generated by Django 5.1 on 2025-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0013_alter_productos_especies_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='bin_pro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
