# Generated by Django 5.1 on 2025-03-11 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0014_alter_productos_bin_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='especies_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cloraciones.especies'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='variedad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cloraciones.variedad'),
        ),
    ]
