# Generated by Django 5.1 on 2025-04-06 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0015_alter_productos_especies_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diluyentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dil', models.TextField(max_length=30)),
            ],
            options={
                'verbose_name': 'Diluyente',
                'verbose_name_plural': 'Diluyentes',
            },
        ),
        migrations.AlterField(
            model_name='cloracion',
            name='aci_clo',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloracion',
            name='hcl_clo',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloracion',
            name='hor_clo',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='cloracion',
            name='phe_clo',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloracion',
            name='ppm_clo',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosificacion',
            name='agu_dos',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosificacion',
            name='ccp_dos',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dosificacion',
            name='cer_dos',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosificacion',
            name='hor_dos',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='dat_ppm',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='hor_ppm',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='phe_ppm',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='bin_pro',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='doa_pro',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='dof_pro',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='dor_pro',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='gas_pro',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='kil_pro',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ren_pro',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='agu_tem',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='amb_tem',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='est_tem',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='hor_tem',
            field=models.TimeField(blank=True, db_index=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='pul_tem',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
