# Generated by Django 5.1 on 2025-04-06 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0016_diluyentes_alter_cloracion_aci_clo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosificacion',
            name='diluyentes_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cloraciones.diluyentes'),
        ),
    ]
