# Generated by Django 5.1 on 2025-04-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0017_dosificacion_diluyentes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosificacion',
            name='diluyentes_id',
        ),
    ]
