# Generated by Django 5.1 on 2025-06-20 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0018_remove_dosificacion_diluyentes_id'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Acción Realizada')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('trabajador_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Registro de Historial',
                'verbose_name_plural': 'Registros de Historial',
                'ordering': ['-timestamp'],
            },
        ),
    ]
