# Generated by Django 5.1 on 2025-06-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0019_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='accion',
            field=models.CharField(choices=[('CREACIÓN', 'Creación'), ('EDICIÓN', 'Edición'), ('ELIMINACIÓN', 'Eliminación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Acción Realizada'),
        ),
    ]
