# Generated by Django 5.1 on 2025-07-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0020_alter_historial_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloracion',
            name='obs_clo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='diluyentes',
            name='nom_dil',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dosificacion',
            name='obs_dos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='especies',
            name='nom_esp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fungicidas',
            name='nom_fun',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='grupocloracion',
            name='loa_gru',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupocloracion',
            name='loh_gru',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupoproductos',
            name='obs_grp',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='grupotemperatura',
            name='obs_grt',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historial',
            name='accion',
            field=models.CharField(choices=[('CREACIÓN', 'Creación'), ('EDICIÓN', 'Edición'), ('ELIMINACIÓN', 'Eliminación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Acción Realizada'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historial',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='lineas',
            name='num_lin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='obs_ppm',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nom_sec',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='apm_tra',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='app_tra',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nom_tra',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rut_tra',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='nom_tur',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='variedad',
            name='nom_var',
            field=models.CharField(max_length=20),
        ),
    ]
