# Generated by Django 5.1 on 2025-07-11 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0021_change_textfield_to_charfield_only'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diluyentes',
            name='nom_dil',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='especies',
            name='nom_esp',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fungicidas',
            name='nom_fun',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='grupocloracion',
            name='loa_gru',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupocloracion',
            name='loh_gru',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupoproductos',
            name='obs_grp',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='grupotemperatura',
            name='obs_grt',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='historial',
            name='accion',
            field=models.CharField(choices=[('CREACIÓN', 'Creación'), ('EDICIÓN', 'Edición'), ('ELIMINACIÓN', 'Eliminación'), ('OTRO', 'Otro')], db_index=True, max_length=20, verbose_name='Acción Realizada'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='lineas',
            name='num_lin',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nom_sec',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='apm_tra',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='app_tra',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nom_tra',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rut_tra',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='nom_tur',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='variedad',
            name='nom_var',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='dia',
            index=models.Index(fields=['dia_dia'], name='Cloraciones_dia_dia_12040c_idx'),
        ),
        migrations.AddIndex(
            model_name='diluyentes',
            index=models.Index(fields=['nom_dil'], name='Cloraciones_nom_dil_a8c32d_idx'),
        ),
        migrations.AddIndex(
            model_name='grupocloracion',
            index=models.Index(fields=['dia_id', 'lineas_id', 'turnos_id'], name='Cloraciones_dia_id__a897b8_idx'),
        ),
        migrations.AddIndex(
            model_name='grupocloracion',
            index=models.Index(fields=['trabajador_id', 'dia_id'], name='Cloraciones_trabaja_065103_idx'),
        ),
        migrations.AddIndex(
            model_name='grupocloracion',
            index=models.Index(fields=['loh_gru', 'loa_gru'], name='Cloraciones_loh_gru_83bdff_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoproductos',
            index=models.Index(fields=['dia_id', 'lineas_id', 'turnos_id'], name='Cloraciones_dia_id__b16535_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoproductos',
            index=models.Index(fields=['trabajador_id', 'dia_id'], name='Cloraciones_trabaja_bcbd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='grupotemperatura',
            index=models.Index(fields=['dia_id', 'lineas_id', 'turnos_id'], name='Cloraciones_dia_id__64b2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='grupotemperatura',
            index=models.Index(fields=['trabajador_id', 'dia_id'], name='Cloraciones_trabaja_ddcb42_idx'),
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['trabajador_id', 'timestamp'], name='Cloraciones_trabaja_65467d_idx'),
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['content_type', 'object_id'], name='Cloraciones_content_c7bb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['accion', 'timestamp'], name='Cloraciones_accion_1798ca_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['nom_tra', 'app_tra'], name='Cloraciones_nom_tra_affb1e_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['user'], name='Cloraciones_user_id_9a21b3_idx'),
        ),
        migrations.AddIndex(
            model_name='variedad',
            index=models.Index(fields=['especies_id', 'nom_var'], name='Cloraciones_especie_0fcce9_idx'),
        ),
    ]
