# Generated by Django 5.1 on 2025-07-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloraciones', '0022_alter_diluyentes_nom_dil_alter_especies_nom_esp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloracion',
            name='obs_clo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dosificacion',
            name='obs_dos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grupoproductos',
            name='obs_grp',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='obs_ppm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
